version: '3.8'
services:
  videomicro:
    container_name: usermicroapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - storage:/var/storage
    restart: unless-stopped
volumes:
  storage:
